services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - 'matrix_postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped

  synapse:
    build: .
    depends_on:
      - postgres
    volumes:
      - 'matrix_synapse_data:/data'
    restart: unless-stopped
    ports:
      - '8008:8008'
      - '8448:8448'
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse.rule=Host(`chat.rahmoundif.dev`)
      - traefik.http.routers.synapse.entrypoints=https
      - traefik.http.routers.synapse.tls=true
      - traefik.http.routers.synapse.tls.certresolver=letsencrypt
      - traefik.http.services.synapse.loadbalancer.server.port=8008
    networks:
      - default
      - coolify

networks:
  coolify:
    external: true

volumes:
  matrix_postgres_data:
    driver: local
  matrix_synapse_data:
    driver: local
