services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - 'matrix_postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped

  synapse:
    image: 'matrixdotorg/synapse:latest'
    depends_on:
      - postgres
    volumes:
      - 'matrix_synapse_data:/data'
      - './homeserver.yaml:/data/homeserver.yaml:ro'
      - './log.config:/data/log.config:ro'
    restart: unless-stopped
    ports:
      - '8008:8008'
      - '8448:8448'

volumes:
  matrix_postgres_data:
    driver: local
  matrix_synapse_data:
    driver: local
