services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - 'matrix_postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped

  synapse:
    build: .
    depends_on:
      - postgres
    volumes:
      - 'matrix_synapse_data:/data'
    restart: unless-stopped
    ports:
      - '8008:8008'
      - '8448:8448'

volumes:
  matrix_postgres_data:
    driver: local
  matrix_synapse_data:
    driver: local
